# Generated by Django 5.1.2 on 2024-12-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.IntegerField(default=0),
        ),
    ]
